### ISSUE TITLE
Clean up reasons

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-lendio#25]
I noticed that the reasons given for rejects could be cleaned up some

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/569/7432566/e60d169a-efee-11e4-9c4f-14378192656a.png)

Why not just "email already in use" and "zip is not in our database"?

**Comment by ros3bud** [comment]
Sometimes the error message will be something such as: "must not be blank" making the name necessary in order to fully understand the error.

**Comment by alexkwolfe** [comment]
That's fine. But in these two cases (at least), the name is extraneous.

**Comment by ros3bud** [comment]
Agreed that the name extraneous. The docs are incomplete so this type of update will need to be iterative. I can keep an eye on the errors though.

**Comment by ros3bud** [comment]
All potential error responses: 
'not_empty' => 'Must not be empty',
'\Valid::unique_email'    => 'Email already in use',
'\Profile::unique_email'    => 'Email already in use',
'validate.login.authenticate' => 'Invalid email or password',
'not_empty_string' => ':field must contain letters',
'\Valid::zip' => 'Zip is not in our database',
'zip' => 'Zip is not in our database',
'\Profile::zip' => 'Zip is not in our database',
'url' => ':field must be a URL, including http:// or https://',
'character_limit' => 'A maximum of :param2 characters are allowed.',
'character_min' => 'A minimum of :param2 characters are required.',
'time_min_vs_max' => 'Time Max Must Be Greater Than Or Equal To Time Min',
'range_min_vs_max' => 'Range Max Must Be Greater Than Or Equal To Range Min',
'rate_min_vs_max' => 'Rate Max Must Be Greater Than Or Equal To Rate Min',
'Upload::type' => 'File must be :param1',
'\Valid::money' => 'Must be a number',
'\Valid::unique_phone' => 'Phone number already in use',
'\Profile::unique_phone' => 'Phone number already in use',
'\Valid::full_name' => 'Must be a first and last name',
'\Valid::ssn' => 'Social Security # must be 9 digits',
'only_options' => 'Must be one of the options',
'unique_product_name' => 'This institution already has a product with this loan type and name',
'not_from_lendio' => 'You entered an invalid email',
'full_name' => 'Must be a first and last name',
'business_name' => 'Must not be empty',
'email'         => ':field must be an email address',
