### ISSUE TITLE
Industry is now required

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-integration-lendio#34]
This should be reflected in the integrations as it is a recent update to the Lendio requirements.

**Comment by cgrayson** [comment]
Already accounted for: 

https://github.com/activeprospect/leadconduit-integration-lendio/blob/master/src/outbound.coffee#L98
&
https://github.com/activeprospect/leadconduit-integration-lendio/blob/master/src/outbound.coffee#L376
