### ISSUE TITLE
update for new posting API

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integration-lendio#39]
The Lendio posting API has been updated. See the [old posting doc](https://drive.google.com/open?id=0Byx5ycIxXRdabHFYdE1vYWJXRE0) vs. the [new posting doc](https://drive.google.com/open?id=0B3snTzjBrjGRNTNBUThNaUFxNkE) to be sure, but following are the changes I see. 

- [ ] add `business_state`
- [ ] add `campaign`
- [ ] add `adgroup`
- [ ] remove `mobile_opt_in`
- [ ] remove `marketplace`

**Comment by alexj** [comment]
I'm concerned with removing `mobile_opt_in`. While it's true that it isn't in their doc, that seems like a possible oversight on their part. Their [example form](https://www.lendio.com/sign_up) includes it, though the id is `signup-mobile-opt-in`. And their is a box with TCPA language in it within their new posting docs under the Field Options section. Please it in for now. 

Plus it's a key value of TF, so we should be passing it through.

**Comment by alexj** [comment]
Lynda, could you please make these change for Lendio when you have a few minutes? For now, please do not remove `mobile_opt_in`.

Thanks.

**Comment by ros3bud** [comment]
Updated in 0.1.0
