### ISSUE TITLE
Adding custom fields of type array is needed but not currently allowed

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-integration-lendio#48]
For the Lendio inbound integration, we need to allow users to POST non-standard fields which are arrays. At this point it does not look like we support this as the data does not show up in the UI. 
<img width="729" alt="screen shot 2015-12-22 at 10 35 48 am" src="https://cloud.githubusercontent.com/assets/3402403/11960374/fcf43bec-a897-11e5-9b2a-f296d73e7ccd.png">
Note that the blank fields were type array. The following is an example of the POST data I used. 

      { "affiliate": "abcd",
        "campaign": "Affiliate",
        "full_name": "lyn T. Tester",
        "adgroup": "adgroup name",
        "business_name": "ActiveProspect Testing",
        "business_street": "123 Pine Street",
        "primary_phone": "(512)255-1234",
        "business_city": "Austin",
        "business_state": "TX",
        "business_zip": "78751",
        "email": "lendiotest@lendio.com",
        "credit_score": "101",
        "average_monthly_sales": "1156",
        "finance_amount": "104",
        "monthly_charges": "10001",
        "industry": "1030",
        "loan_purpose": [798],
        "accounts_receivable_amount": "934",
        "primary_customer": "787",
        "time_in_business": "111",
        "collateral_available": [920],
        "current_financing": "true",
        "time_to_funding": "884",
        "comments": "I would like to sign up.",
        "mobile_opt_in": "true"
      }

**Comment by alexkwolfe** [comment]
What does the event data look like? If it's not being displayed properly, this could be a display bug.

**Comment by ros3bud** [comment]
It could be indeed, because the data is actually getting posted to Lendio: 

{
  "affiliate": 2001480387,
  "monthly_charges": "10001",
  "collateral_available": [
    920
  ],
  "mobile_opt_in": 1,
  "full_name": "Lyn T. Tester",
  "email": "lendiotest@lendio.com",
  "primary_phone": "5122551234",
  "comments": "I would like to sign up.",
  "business_street": "123 Pine Street",
  "business_city": "Austin",
  "business_state": "TX",
  "primary_customer": "787",
  "current_financing": 1,
  "finance_amount": "104",
  "loan_purpose": [
    798
  ],
  "credit_score": "101",
  "time_in_business": "111",
  "average_monthly_sales": "1156",
  "industry": "1030",
  "time_to_funding": "884",
  "business_name": "Activeprospect Testing"
}

**Comment by alexkwolfe** [comment]
OK. Please let the UI team know by filing an issue in the leadconduit-client repo.

**Comment by ros3bud** [comment]
Ok, will do.
