### ISSUE TITLE
Standardize Lendio Inbound

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-integration-lendio#54]
Rather than using additional fields for Lendio IDs, the values in Lendio inbound should be added to our internal standard fields. This means taking the ID values and determining what value they represent before assigning them to a standard field. This will allow the inbound integration to be more widely usable within our software.

**Comment by alexkwolfe** [comment]
Make sure the inbound integration returns the same HTTP status code as the Lendio API. Also make sure that the Lendio redirect URL is returned in the inbound response.

**Comment by ros3bud** [comment]
solved in 1.0.0
